language: elixir
elixir:
  - 1.4.4
otp_release:
  - 18.2
env:
  - MIX_ENV=test
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix test
branches:
  only:
    - master
